// biome-ignore-all assist/source/organizeImports: import order matches generated entry order
"use client";

// Generated by scripts/generate-component-catalog.mjs. Do not edit.
import { catalogContract as catalogContract1 } from "@/app/(site)/dashboard/_components/commands/DashboardCommandPalette.catalog";
import { catalogContract as catalogContract2 } from "@/app/(site)/dashboard/_components/entities/account/AccountIdentity.catalog";
import { catalogContract as catalogContract3 } from "@/app/(site)/dashboard/_components/entities/member/MemberAvatarList.catalog";
import { catalogContract as catalogContract4 } from "@/app/(site)/dashboard/_components/entities/member/MemberIdentity.catalog";
import { catalogContract as catalogContract5 } from "@/app/(site)/dashboard/_components/entities/member/MemberMention.catalog";
import { catalogContract as catalogContract6 } from "@/app/(site)/dashboard/_components/entities/member/MemberRoleChip.catalog";
import { catalogContract as catalogContract7 } from "@/app/(site)/dashboard/_components/entities/member/MemberSelector.catalog";
import { catalogContract as catalogContract8 } from "@/app/(site)/dashboard/_components/entities/organization/OrganizationIdentity.catalog";
import { catalogContract as catalogContract9 } from "@/app/(site)/dashboard/_components/entities/organization/OrganizationSelector.catalog";
import { catalogContract as catalogContract10 } from "@/app/(site)/dashboard/_components/entities/record/RecordIdentity.catalog";
import { catalogContract as catalogContract11 } from "@/app/(site)/dashboard/_components/entities/record/RecordSelector.catalog";
import { catalogContract as catalogContract12 } from "@/app/(site)/dashboard/_components/entities/record/RecordStatusChip.catalog";
import { catalogContract as catalogContract13 } from "@/app/(site)/dashboard/_components/entities/record/RecordToolCall.catalog";
import { catalogContract as catalogContract14 } from "@/components/branding/Logo.catalog";
import { catalogContract as catalogContract15 } from "@/components/composites/markdown/Markdown.catalog";
import { catalogContract as catalogContract16 } from "@/components/domain/assistant/message/Message.catalog";
import { catalogContract as catalogContract17 } from "@/components/domain/assistant/status/Status.catalog";
import { catalogContract as catalogContract18 } from "@/components/ui/foundations/Focus.catalog";
import { catalogContract as catalogContract19 } from "@/components/ui/foundations/MotionProvider.catalog";
import { catalogContract as catalogContract20 } from "@/components/ui/foundations/MotionTiming.catalog";
import { catalogContract as catalogContract21 } from "@/components/ui/foundations/Settings.catalog";
import { catalogContract as catalogContract22 } from "@/components/ui/foundations/SurfaceTint.catalog";
import { catalogContract as catalogContract23 } from "@/components/ui/helpers/CopyAction.catalog";
import { catalogContract as catalogContract24 } from "@/components/ui/helpers/IconSwap.catalog";
import { catalogContract as catalogContract25 } from "@/components/ui/icons/Icon.catalog";
import { catalogContract as catalogContract26 } from "@/components/ui/input/SignatureInput.catalog";
import { catalogContract as catalogContract27 } from "@/components/ui/input/choice/ChoiceField.catalog";
import { catalogContract as catalogContract28 } from "@/components/ui/input/choice/ChoiceIndicators.catalog";
import { catalogContract as catalogContract29 } from "@/components/ui/input/choice/MultiselectInput.catalog";
import { catalogContract as catalogContract30 } from "@/components/ui/input/choice/RadioInput.catalog";
import { catalogContract as catalogContract31 } from "@/components/ui/input/choice/ToggleInput.catalog";
import { catalogContract as catalogContract32 } from "@/components/ui/input/color/ColorInput.catalog";
import { catalogContract as catalogContract33 } from "@/components/ui/input/color/ColorSwatchInput.catalog";
import { catalogContract as catalogContract34 } from "@/components/ui/input/date/DateInput.catalog";
import { catalogContract as catalogContract35 } from "@/components/ui/input/date/DateRangeInput.catalog";
import { catalogContract as catalogContract36 } from "@/components/ui/input/editable/EditableTextField.catalog";
import { catalogContract as catalogContract37 } from "@/components/ui/input/files/FileInput.catalog";
import { catalogContract as catalogContract38 } from "@/components/ui/input/files/ProfilePictureInput.catalog";
import { catalogContract as catalogContract39 } from "@/components/ui/input/numeric/NumberInput.catalog";
import { catalogContract as catalogContract40 } from "@/components/ui/input/numeric/SliderInput.catalog";
import { catalogContract as catalogContract41 } from "@/components/ui/input/numeric/UnitNumberInput.catalog";
import { catalogContract as catalogContract42 } from "@/components/ui/input/selection/ButtonMultiSelectInput.catalog";
import { catalogContract as catalogContract43 } from "@/components/ui/input/selection/ComboboxMultiSelectInput.catalog";
import { catalogContract as catalogContract44 } from "@/components/ui/input/selection/ComboboxTextInput.catalog";
import { catalogContract as catalogContract45 } from "@/components/ui/input/selection/SelectInput.catalog";
import { catalogContract as catalogContract46 } from "@/components/ui/input/text/EmailInput.catalog";
import { catalogContract as catalogContract47 } from "@/components/ui/input/text/PasswordInput.catalog";
import { catalogContract as catalogContract48 } from "@/components/ui/input/text/PhoneInput.catalog";
import { catalogContract as catalogContract49 } from "@/components/ui/input/text/SpamProtectionFields.catalog";
import { catalogContract as catalogContract50 } from "@/components/ui/input/text/TextAreaInput.catalog";
import { catalogContract as catalogContract51 } from "@/components/ui/input/text/TextInput.catalog";
import { catalogContract as catalogContract52 } from "@/components/ui/misc/Chip.catalog";
import { catalogContract as catalogContract53 } from "@/components/ui/misc/CopyField.catalog";
import { catalogContract as catalogContract54 } from "@/components/ui/misc/HealthCheckIndicator.catalog";
import { catalogContract as catalogContract55 } from "@/components/ui/misc/ImageSwitcher.catalog";
import { catalogContract as catalogContract56 } from "@/components/ui/misc/InspectableImage.catalog";
import { catalogContract as catalogContract57 } from "@/components/ui/misc/InteractionGate.catalog";
import { catalogContract as catalogContract58 } from "@/components/ui/misc/Loader.catalog";
import { catalogContract as catalogContract59 } from "@/components/ui/misc/PaginationControls.catalog";
import { catalogContract as catalogContract60 } from "@/components/ui/misc/ProfilePicture.catalog";
import { catalogContract as catalogContract61 } from "@/components/ui/misc/ScrollBorders.catalog";
import { catalogContract as catalogContract62 } from "@/components/ui/misc/SegmentedControl.catalog";
import { catalogContract as catalogContract63 } from "@/components/ui/misc/Skeleton.catalog";
import { catalogContract as catalogContract64 } from "@/components/ui/misc/SocialLinks.catalog";
import { catalogContract as catalogContract65 } from "@/components/ui/misc/StepIndicator.catalog";
import { catalogContract as catalogContract66 } from "@/components/ui/misc/SuspenseBoundary.catalog";
import { catalogContract as catalogContract67 } from "@/components/ui/misc/Tooltip.catalog";
import { catalogContract as catalogContract68 } from "@/components/ui/misc/accordion/Accordion.catalog";
import { catalogContract as catalogContract69 } from "@/components/ui/misc/state/State.catalog";
import { catalogContract as catalogContract70 } from "@/components/ui/motion/LetterWave.catalog";
import { catalogContract as catalogContract71 } from "@/components/ui/motion/auto-cycle/AutoCycle.catalog";
import { catalogContract as catalogContract72 } from "@/components/ui/motion/reveal/Reveal.catalog";
import { catalogContract as catalogContract73 } from "@/components/ui/motion/scroll/Scroll.catalog";
import { catalogContract as catalogContract74 } from "@/components/ui/overlays/Portal.catalog";
import { catalogContract as catalogContract75 } from "@/components/ui/overlays/modal/ConfirmationModal.catalog";
import { catalogContract as catalogContract76 } from "@/components/ui/overlays/modal/ImageInspectModal.catalog";
import { catalogContract as catalogContract77 } from "@/components/ui/overlays/modal/Modal.catalog";
import { catalogContract as catalogContract78 } from "@/components/ui/overlays/modal/ModalForm.catalog";
import { catalogContract as catalogContract79 } from "@/components/ui/overlays/toast/Toast.catalog";
import { catalogContract as catalogContract80 } from "@/components/ui/primitives/Button.catalog";
import { catalogContract as catalogContract81 } from "@/components/ui/primitives/Divider.catalog";
import { catalogContract as catalogContract82 } from "@/components/ui/primitives/Dropdown.catalog";
import { catalogContract as catalogContract83 } from "@/components/ui/primitives/Field.catalog";
import { catalogContract as catalogContract84 } from "@/components/ui/primitives/InputFrame.catalog";
import { catalogContract as catalogContract85 } from "@/components/ui/primitives/Listbox.catalog";
import { catalogContract as catalogContract86 } from "@/components/ui/primitives/Section.catalog";
import { catalogContract as catalogContract87 } from "@/components/ui/primitives/StatusMessage.catalog";
import { catalogContract as catalogContract88 } from "@/components/ui/primitives/Text.catalog";
import { catalogContract as catalogContract89 } from "@/components/ui/primitives/surfaces/Surfaces.catalog";
import { catalogContract as catalogContract90 } from "@/components/ui/time/DateAgo.catalog";
import { catalogContract as catalogContract91 } from "@/components/ui/time/DateIndicator.catalog";

export const componentCatalog = [
	catalogContract1,
	catalogContract2,
	catalogContract3,
	catalogContract4,
	catalogContract5,
	catalogContract6,
	catalogContract7,
	catalogContract8,
	catalogContract9,
	catalogContract10,
	catalogContract11,
	catalogContract12,
	catalogContract13,
	catalogContract14,
	catalogContract15,
	catalogContract16,
	catalogContract17,
	catalogContract18,
	catalogContract19,
	catalogContract20,
	catalogContract21,
	catalogContract22,
	catalogContract23,
	catalogContract24,
	catalogContract25,
	catalogContract26,
	catalogContract27,
	catalogContract28,
	catalogContract29,
	catalogContract30,
	catalogContract31,
	catalogContract32,
	catalogContract33,
	catalogContract34,
	catalogContract35,
	catalogContract36,
	catalogContract37,
	catalogContract38,
	catalogContract39,
	catalogContract40,
	catalogContract41,
	catalogContract42,
	catalogContract43,
	catalogContract44,
	catalogContract45,
	catalogContract46,
	catalogContract47,
	catalogContract48,
	catalogContract49,
	catalogContract50,
	catalogContract51,
	catalogContract52,
	catalogContract53,
	catalogContract54,
	catalogContract55,
	catalogContract56,
	catalogContract57,
	catalogContract58,
	catalogContract59,
	catalogContract60,
	catalogContract61,
	catalogContract62,
	catalogContract63,
	catalogContract64,
	catalogContract65,
	catalogContract66,
	catalogContract67,
	catalogContract68,
	catalogContract69,
	catalogContract70,
	catalogContract71,
	catalogContract72,
	catalogContract73,
	catalogContract74,
	catalogContract75,
	catalogContract76,
	catalogContract77,
	catalogContract78,
	catalogContract79,
	catalogContract80,
	catalogContract81,
	catalogContract82,
	catalogContract83,
	catalogContract84,
	catalogContract85,
	catalogContract86,
	catalogContract87,
	catalogContract88,
	catalogContract89,
	catalogContract90,
	catalogContract91,
] as const;
