const overrideFiles = [
	"src/app/globals.css",
	"src/components/composites/markdown/index.ts",
	"src/app/(site)/(marketing)/_components/layout/Footer.tsx",
	"src/app/(site)/(marketing)/_components/layout/Header.tsx",
	"src/app/(site)/(marketing)/_components/layout/HeaderCompact.tsx",
	"src/app/(site)/(marketing)/_components/layout/HeaderFull.tsx",
	"src/app/(site)/(marketing)/_components/layout/HeaderMenuContent.tsx",
	"src/app/(site)/(marketing)/_components/layout/MarketingShell.tsx",
	"src/app/(site)/(marketing)/contact/page.tsx",
	"src/app/(site)/(dev)/internal/intelligence/_components/InternalCard.tsx",
	"src/app/(site)/(dev)/internal/intelligence/BenchmarkRunToggle.tsx",
	"src/app/(site)/(dev)/internal/intelligence/page.tsx",
	"src/app/(site)/(marketing)/layout.tsx",
	"src/app/(site)/layout.tsx",
	"src/components/ui/input/index.ts",
	"src/components/ui/misc/index.ts",
	"src/components/ui/input/choice/ChoiceField.tsx",
	"src/components/ui/input/date/index.ts",
	"src/components/ui/input/choice/ChoiceIndicators.tsx",
	"src/components/ui/input/choice/MultiselectInput.tsx",
	"src/components/ui/input/choice/RadioInput.tsx",
	"src/components/ui/input/selection/SelectInput.tsx",
	"src/components/ui/input/text/TextInput.tsx",
	"src/components/ui/input/choice/ToggleInput.tsx",
	"src/components/ui/overlays/modal/ConfirmationModal.tsx",
	"src/components/ui/overlays/modal/ImageInspectModal.tsx",
	"src/components/ui/overlays/modal/ModalShell.tsx",
	"src/components/ui/overlays/toast/ToastHost.tsx",
	"src/components/ui/primitives/Button.tsx",
	"src/components/ui/primitives/Field.tsx",
	"src/components/ui/primitives/InputFrame.tsx",
	"src/components/ui/primitives/Text.tsx",
	"src/config/routes.ts",
	"src/lib/api/index.ts",
	"src/lib/feedback/toast.ts",
	"src/lib/marketing-content/fallback.ts",
	"src/lib/marketing-content/links.ts",
	"src/lib/marketing-content/resolvers.ts",
	"src/lib/marketing-content/sections/homeHero/HomeHeroSection.tsx",
	"src/lib/marketing-content/types.ts",
	"src/lib/routes.ts",
];

export const thinStartProfile = {
	schemaVersion: 2,
	id: "thin-start",
	description:
		"A complete, minimal Averlo workspace with the shared visual foundation and a filesystem-backed live surface.",
	defaultOutput: ".thin-start/workspace",
	content: {
		supported: ["static", "payload-ready"],
		default: "payload-ready",
	},
	assembly: {
		coreScripts: [
			"build",
			"dev",
			"dev:agent",
			"dev:inspect",
			"dev:local",
			"dev:preview",
			"dev:user",
			"format",
			"lint",
			"orchestration",
			"orchestration-state",
			"postbuild",
			"postinstall",
			"predev:inspect",
			"predev:local",
			"predev:preview",
			"start",
			"typecheck",
			"verify",
			"verify:build",
			"verify:component-skeletons",
			"verify:modals",
			"verify:route-skeletons",
			"verify:smoke",
			"verify:static",
			"verify:surface-contracts",
		],
		coreDependencies: [
			"@phosphor-icons/react",
			"@radix-ui/react-slot",
			"@tanstack/react-hotkeys",
			"class-variance-authority",
			"clsx",
			"libphonenumber-js",
			"motion",
			"next",
			"next-sitemap",
			"react",
			"react-dom",
			"react-markdown",
			"react-phone-number-input",
			"react-responsive",
			"remark-gfm",
			"sonner",
		],
		coreDevDependencies: [
			"@biomejs/biome",
			"@tailwindcss/postcss",
			"@types/node",
			"@types/react",
			"@types/react-dom",
			"code-inspector-plugin",
			"playwright",
			"tailwindcss",
			"typescript",
		],
		surfaces: ["marketing", "intelligence", "payload"],
		sourceInventory: "template-assembly/thin-start-src-files.json",
		verificationCommands: [
			"npm run verify:static",
			"npm run build",
			"npm run verify:smoke",
		],
	},
	overridesRoot: "template-profiles/thin-start/overrides",
	sharedFiles: [
		"src/components/ui/primitives/Panel.tsx",
		"src/components/ui/primitives/Card.tsx",
		"src/components/ui/misc/Skeleton.tsx",
		"src/lib/marketing-content/sections/homeHero/HomeHeroSurfaceAssembly.tsx",
	],
	overrides: overrideFiles.map((target) => ({
		source: `template-profiles/thin-start/overrides/${target}`,
		target,
	})),
	apiReview: {
		allowedUiImports: [
			"@/components/ui/misc",
			"@/components/ui/misc/Skeleton",
			"@/components/ui/input",
			"@/components/ui/input/InputSkeleton",
			"@/components/ui/primitives/Button",
			"@/components/ui/primitives/Card",
			"@/components/ui/primitives/Panel",
			"@/components/ui/primitives/Text",
			"@/components/ui/primitives/Section",
			"@/components/ui/primitives/Field",
			"@/components/ui/primitives/InputFrame",
			"@/components/ui/primitives/dropdown",
			"@/components/ui/primitives/dropdownStyles",
			"@/components/ui/input/choice/ChoiceField",
			"@/components/ui/input/choice/ChoiceIndicators",
		],
		allowedUiPrefixes: [
			"@/components/ui/foundations/",
			"@/components/ui/motion",
			"@/components/ui/overlays/",
		],
		allowedCompositePrefixes: ["@/components/composites/markdown"],
		broadUiPrefixes: [
			"@/components/ui/misc/",
			"@/components/ui/helpers/",
			"@/components/ui/icons/",
			"@/components/ui/time/",
		],
		compatibilityMarkerExemptions: [
			"src/app/(site)/(dev)/internal/intelligence/page.tsx",
			"src/proxy.ts",
			"src/lib/template-intelligence/index.ts",
			"src/components/ui/motion/reveal/legacyCore.tsx",
		],
	},
	verification: {
		requiredFiles: [
			"src/app/(site)/(marketing)/(home)/page.tsx",
			"src/app/(site)/(marketing)/contact/page.tsx",
			"src/components/ui/misc/index.ts",
			"src/components/ui/misc/Skeleton.tsx",
			"src/components/ui/input/index.ts",
			"src/components/ui/input/date/DateInput.tsx",
			"src/components/ui/input/date/index.ts",
			"src/components/ui/primitives/Panel.tsx",
			"src/components/ui/primitives/Card.tsx",
			"src/components/ui/overlays/modal/ModalCard.tsx",
			"src/components/ui/overlays/toast/ToastHost.tsx",
			"src/app/(site)/(dev)/internal/intelligence/page.tsx",
		],
		forbiddenPaths: [
			"src/app/(site)/(auth)",
			"src/app/api/auth",
			"src/app/api/debug",
			"src/app/(site)/dashboard",
			"src/app/api/feedback",
			"src/app/api/platform",
			"src/app/api/support",
			"src/app/(site)/(dev)/internal/demo",
			"scripts/scroll-performance",
			"src/lib/auth",
		],
		forbiddenPackages: [
			"@mdxeditor/editor",
			"micromark",
			"micromark-extension-directive",
			"micromark-extension-mdx-jsx",
			"micromark-extension-mdx-md",
		],
		commands: [
			"npm run review:thin-start-api -- --strict",
			"npm run typecheck",
			"npm run build",
		],
	},
};

export default thinStartProfile;
