const overrideFiles = [
	"src/app/globals.css",
	"src/components/composites/markdown/index.ts",
	"src/app/(site)/_components/layout/Footer.tsx",
	"src/app/(site)/_components/layout/Header.tsx",
	"src/app/(site)/_components/layout/HeaderCompact.tsx",
	"src/app/(site)/_components/layout/HeaderFull.tsx",
	"src/app/(site)/_components/layout/HeaderMenuContent.tsx",
	"src/app/(site)/_components/layout/siteLayout.ts",
	"src/app/(site)/(marketing)/layout.tsx",
	"src/app/(site)/layout.tsx",
	"src/components/ui/input/index.ts",
	"src/components/ui/misc/index.ts",
	"src/components/ui/input/choice/ChoiceField.tsx",
	"src/components/ui/input/date/index.ts",
	"src/components/ui/input/choice/ChoiceIndicators.tsx",
	"src/components/ui/input/choice/MultiselectInput.tsx",
	"src/components/ui/input/choice/RadioInput.tsx",
	"src/components/ui/input/selection/SelectInput.tsx",
	"src/components/ui/input/text/TextInput.tsx",
	"src/components/ui/input/choice/ToggleInput.tsx",
	"src/components/ui/overlays/modal/ConfirmationModal.tsx",
	"src/components/ui/overlays/modal/ImageInspectModal.tsx",
	"src/components/ui/overlays/modal/ModalShell.tsx",
	"src/components/ui/overlays/toast/ToastHost.tsx",
	"src/components/ui/primitives/Button.tsx",
	"src/components/ui/primitives/Field.tsx",
	"src/components/ui/primitives/InputFrame.tsx",
	"src/components/ui/primitives/Text.tsx",
	"src/lib/api/index.ts",
	"src/lib/feedback/toast.ts",
	"src/lib/marketing-content/fallback.ts",
	"src/lib/marketing-content/links.ts",
	"src/lib/marketing-content/resolvers.ts",
	"src/lib/marketing-content/sections/homeHero/HomeHeroSection.tsx",
	"src/lib/marketing-content/types.ts",
];

export const thinStartProfile = {
	schemaVersion: 2,
	id: "thin-start",
	description:
		"A complete, minimal Averlo workspace with the shared visual foundation and a filesystem-backed live surface.",
	defaultOutput: ".thin-start/workspace",
	content: {
		supported: ["static", "payload-ready"],
		default: "payload-ready",
	},
	assembly: {
		coreScripts: [
			"build-storybook",
			"build",
			"design-system:evidence",
			"dev",
			"dev:local",
			"preview:tunnel",
			"preview:capture",
			"format",
			"lint",
			"postbuild",
			"postinstall",
			"start",
			"storybook",
			"storybook:preview",
			"storybook:status",
			"storybook:stop",
			"test-storybook",
			"typecheck",
			"verify",
			"verify:build",
			"verify:component-skeletons",
			"verify:modals",
			"verify:route-skeletons",
			"verify:smoke",
			"verify:static",
			"verify:surface-contracts",
			"verify:retired-semantic-service",
			"verify:retired-template-intelligence",
			"verify:skill-references",
			"verify:route-surfaces",
			"verify:route-metadata",
			"verify:design-system-evidence",
			"verify:storybook-preview",
			"verify:preview-capture",
			"verify:dev-server-shutdown",
		],
		coreDependencies: [
			"@phosphor-icons/react",
			"@radix-ui/react-slot",
			"@tanstack/react-hotkeys",
			"class-variance-authority",
			"clsx",
			"libphonenumber-js",
			"motion",
			"next",
			"next-sitemap",
			"react",
			"react-dom",
			"react-markdown",
			"react-phone-number-input",
			"remark-gfm",
			"sonner",
		],
		coreDevDependencies: [
			"@biomejs/biome",
			"@chromatic-com/storybook",
			"@storybook/addon-a11y",
			"@storybook/addon-docs",
			"@storybook/addon-mcp",
			"@storybook/addon-vitest",
			"@storybook/nextjs-vite",
			"@tailwindcss/postcss",
			"@types/node",
			"@types/react",
			"@types/react-dom",
			"@vitest/browser-playwright",
			"@vitest/coverage-v8",
			"playwright",
			"storybook",
			"tailwindcss",
			"tsx",
			"typescript",
			"vite",
			"vitest",
		],
		surfaces: ["marketing", "testing", "payload"],
		sourceInventory: "template-assembly/thin-start-src-files.json",
		verificationCommands: [
			"npm run verify:static",
			"npm run verify:marketing-sections",
			"npm run verify:site-layout",
			"npm run build",
			"npm run verify:smoke",
		],
	},
	overridesRoot: "template-profiles/thin-start/overrides",
	sharedFiles: [
		"src/components/ui/primitives/surfaces/AGENTS.md",
		"src/components/ui/primitives/surfaces/Panel.tsx",
		"src/components/ui/primitives/surfaces/Card.tsx",
		"src/components/ui/primitives/surfaces/Float.tsx",
		"src/components/ui/primitives/surfaces/index.ts",
		"src/components/ui/primitives/surfaces/surfaceStyles.ts",
		"src/components/ui/misc/Skeleton.tsx",
		"src/components/ui/icons/customRegistry.tsx",
		"src/components/ui/icons/iconRegistry.tsx",
		"src/components/ui/icons/phosphorRegistry.tsx",
		"src/lib/marketing-content/sections/homeHero/HomeHeroPreviewCollage.tsx",
	],
	overrides: overrideFiles.map((target) => ({
		source: `template-profiles/thin-start/overrides/${target}`,
		target,
	})),
	apiReview: {
		allowedUiImports: [
			"@/components/ui/misc",
			"@/components/ui/misc/Skeleton",
			"@/components/ui/input",
			"@/components/ui/input/InputSkeleton",
			"@/components/ui/primitives/Button",
			"@/components/ui/primitives/Divider",
			"@/components/ui/primitives/surfaces",
			"@/components/ui/primitives/Text",
			"@/components/ui/primitives/Section",
			"@/components/ui/primitives/Field",
			"@/components/ui/primitives/InputFrame",
			"@/components/ui/primitives/StatusMessage",
			"@/components/ui/primitives/dropdown",
			"@/components/ui/primitives/dropdownStyles",
			"@/components/ui/input/choice/ChoiceField",
			"@/components/ui/input/choice/ChoiceIndicators",
			"@/components/ui/time/DateIndicator",
		],
		allowedUiPrefixes: [
			"@/components/ui/foundations/",
			"@/components/ui/motion/auto-cycle",
			"@/components/ui/motion/effect",
			"@/components/ui/motion/source",
			"@/components/ui/overlays/",
			"@/components/ui/primitives/surfaces/",
		],
		allowedCompositePrefixes: ["@/components/composites/markdown"],
		broadUiPrefixes: [
			"@/components/ui/misc/",
			"@/components/ui/helpers/",
			"@/components/ui/icons/",
			"@/components/ui/time/",
		],
		compatibilityMarkerExemptions: ["src/proxy.ts"],
	},
	verification: {
		requiredFiles: [
			"src/app/(site)/(marketing)/(home)/page.tsx",
			"src/app/(site)/(marketing)/contact/page.tsx",
			"src/app/(site)/(marketing)/document/page.tsx",
			"src/components/domain/marketing/DocumentPage.tsx",
			"src/components/ui/misc/index.ts",
			"src/components/ui/misc/Skeleton.tsx",
			"src/components/ui/input/index.ts",
			"src/components/ui/input/date/DateInput.tsx",
			"src/components/ui/input/date/index.ts",
			"src/components/ui/primitives/surfaces/AGENTS.md",
			"src/components/ui/primitives/surfaces/Panel.tsx",
			"src/components/ui/primitives/surfaces/Card.tsx",
			"src/components/ui/primitives/surfaces/Float.tsx",
			"src/components/ui/primitives/surfaces/index.ts",
			"src/components/ui/primitives/surfaces/surfaceStyles.ts",
			"src/components/ui/overlays/modal/ModalCard.tsx",
			"src/components/ui/overlays/toast/ToastHost.tsx",
		],
		forbiddenPaths: [
			"src/app/(component-export)",
			"src/app/(site)/(auth)",
			"src/app/api/auth",
			"src/app/api/debug",
			"src/app/(site)/dashboard",
			"src/app/api/feedback",
			"src/app/api/platform",
			"src/app/api/support",
			"src/app/(site)/(dev)/internal/demo",
			"src/config/componentExport.ts",
			"src/lib/component-catalog",
			"scripts/generate-component-catalog.mjs",
			"scripts/verify/verify-component-sweep.ts",
			"scripts/scroll-performance",
			"src/lib/auth",
		],
		forbiddenPackages: [
			"@mdxeditor/editor",
			"micromark",
			"micromark-extension-directive",
			"micromark-extension-mdx-jsx",
			"micromark-extension-mdx-md",
		],
		commands: [
			"npm run review:thin-start-api -- --strict",
			"npm run typecheck",
			"npm run build",
		],
	},
};

export default thinStartProfile;
