import type { RelatedInfo } from "./types";

export const relatedMap: Record<string, RelatedInfo> = {
	Logo: { uses: [], usedIn: ["Footer", "HeaderCompact", "HeaderFull"] },
	Header: { uses: ["HeaderCompact", "HeaderFull"], usedIn: [] },
	HeaderFull: {
		uses: ["Button", "HeaderMenuContent", "IconSwap", "Logo"],
		usedIn: ["Header"],
	},
	HeaderCompact: {
		uses: ["Button", "HeaderMenuContent", "Logo", "ScrollBorders"],
		usedIn: ["Header"],
	},
	HeaderMenuContent: {
		uses: ["Button", "Icon", "InputFrame", "Text"],
		usedIn: ["HeaderCompact", "HeaderFull"],
	},
	"Markdown.Render": {
		uses: ["Button", "ChoiceIndicatorMulti", "Text", "focus"],
		usedIn: [],
	},
	Footer: { uses: ["Button", "Logo", "Text"], usedIn: [] },
	FormValidationClientMount: { uses: [], usedIn: [] },
	ModalClientMount: { uses: ["ModalHost"], usedIn: [] },
	ToastClientMount: { uses: ["ToastHost"], usedIn: [] },
	IconSwap: {
		uses: [],
		usedIn: [
			"Accordion",
			"CopyField",
			"CopyStatusIcon",
			"PasswordInput",
			"PhoneInput",
			"ToastHost",
		],
	},
	Icon: {
		uses: ["customRegistry", "iconRegistry"],
		usedIn: [
			"Accordion",
			"Button",
			"ChoiceIndicatorMulti",
			"ChoiceIndicatorRadio",
			"ChoiceIndicatorToggle",
			"ComboboxMultiSelectInput",
			"CopyStatusIcon",
			"CopyField",
			"DateRangeInput",
			"Dropdown",
			"ErrorState",
			"HeaderCompact",
			"Loader",
			"PasswordInput",
			"PhoneInput",
			"ProfilePictureInput",
			"SegmentedControl",
			"SelectInput",
			"SocialLinks",
			"StateIndicator",
			"ToastHost",
		],
	},
	customRegistry: { uses: [], usedIn: ["Button", "Icon", "iconRegistry"] },
	iconRegistry: {
		uses: ["customRegistry"],
		usedIn: ["Icon", "phosphorRegistry"],
	},
	phosphorRegistry: { uses: ["iconRegistry"], usedIn: [] },
	Text: {
		uses: ["Skeleton"],
		usedIn: [
			"Accordion",
			"Button",
			"ChoiceField",
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"ConfirmationModal",
			"CopyField",
			"DateAgo",
			"DateIndicator",
			"DateRangeInput",
			"EditableTextField",
			"Field",
			"Footer",
			"Listbox",
			"Markdown.Render",
			"PhoneInput",
			"ProfilePicture",
			"SegmentedControl",
			"SelectInput",
			"StateIndicator",
			"ToastHost",
			"FileInput",
		],
	},
	Button: {
		uses: ["Icon", "Loader", "Skeleton", "Text", "focus", "customRegistry"],
		usedIn: [
			"Accordion",
			"ButtonMultiSelectInput",
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"ConfirmationModal",
			"CopyField",
			"EditableTextField",
			"FileInput",
			"Footer",
			"HeaderCompact",
			"HeaderFull",
			"ImageInspectModal",
			"InspectableImage",
			"Listbox",
			"Markdown.Render",
			"PasswordInput",
			"PhoneInput",
			"ProfilePictureInput",
			"SegmentedControl",
			"SelectInput",
			"SocialLinks",
			"StateIndicator",
			"ToastHost",
			"FileInput",
		],
	},
	Chip: {
		uses: ["Icon", "Skeleton", "focus"],
		usedIn: ["FilePreview", "HealthCheckIndicator", "ProfilePicture"],
	},
	InputFrame: {
		uses: ["focus"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"DateRangeInput",
			"EditableTextField",
			"EmailInput",
			"NumberInput",
			"PasswordInput",
			"PhoneInput",
			"SelectInput",
			"SliderInput",
			"TextAreaInput",
			"TextInput",
		],
	},
	Dropdown: {
		uses: ["Button", "Icon", "Listbox", "Portal"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"DateRangeInput",
			"PhoneInput",
			"SelectInput",
		],
	},
	Card: { uses: ["Panel"], usedIn: [] },
	Panel: { uses: [], usedIn: ["Card", "ModalShell", "ToastHost"] },
	Divider: { uses: [], usedIn: [] },
	Section: { uses: [], usedIn: [] },
	Field: {
		uses: ["Text"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"EditableTextField",
			"EmailInput",
			"ButtonMultiSelectInput",
			"MultiselectInput",
			"NumberInput",
			"PasswordInput",
			"PhoneInput",
			"ProfilePictureInput",
			"RadioInput",
			"SelectInput",
			"SliderInput",
			"TextAreaInput",
			"TextInput",
			"ToggleInput",
		],
	},
	Listbox: {
		uses: ["Button", "Text", "dropdownStyles"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"DateRangeInput",
			"PhoneInput",
			"SelectInput",
		],
	},
	dropdownStyles: {
		uses: [],
		usedIn: [
			"ComboboxMultiSelectInput",
			"ComboboxTextInput",
			"Listbox",
			"PhoneInput",
			"SelectInput",
		],
	},
	DateAgo: { uses: ["Text"], usedIn: [] },
	DateIndicator: { uses: ["Text"], usedIn: [] },
	SettingsProvider: { uses: [], usedIn: [] },
	useSettingsContext: { uses: [], usedIn: [] },
	focus: {
		uses: [],
		usedIn: [
			"Button",
			"ChoiceIndicatorMulti",
			"ChoiceIndicatorRadio",
			"ChoiceIndicatorToggle",
			"DateRangeInput",
			"InputFrame",
			"Markdown.Render",
		],
	},
	spring: { uses: [], usedIn: ["Accordion", "SegmentedControl", "ToastHost"] },
	motionTiming: { uses: [], usedIn: ["SuspenseBoundary", "Reveal.Scramble"] },
	createApiClient: { uses: [], usedIn: ["checkHealth"] },
	createMockFetch: { uses: [], usedIn: [] },
	checkHealth: { uses: ["createApiClient"], usedIn: [] },
	MotionScene: {
		uses: ["Reveal.Root", "Reveal.List", "Reveal.Image", "Reveal.Scramble"],
		usedIn: [],
	},
	ActiveStageHost: { uses: ["MotionScene"], usedIn: [] },
	"Reveal.Root": { uses: [], usedIn: [] },
	"Reveal.List": { uses: ["Reveal.Item"], usedIn: [] },
	"Reveal.Item": { uses: [], usedIn: ["Reveal.List"] },
	"Reveal.Image": {
		uses: ["Reveal.Item", "Skeleton", "motionTiming"],
		usedIn: ["ImageInspectModal"],
	},
	"Reveal.Text": { uses: ["Reveal.Item"], usedIn: [] },
	"Reveal.HighlightText": { uses: ["Reveal.Item", "motionTiming"], usedIn: [] },
	"Reveal.Numeric": { uses: ["MotionScene", "spring"], usedIn: [] },
	LetterWave: { uses: ["Text"], usedIn: [] },
	"Reveal.Scramble": { uses: ["motionTiming"], usedIn: [] },
	ScrollHighlightText: { uses: ["spring"], usedIn: [] },
	ScrollLag: { uses: [], usedIn: [] },
	ScrollParallax: { uses: [], usedIn: [] },
	ScrollWidth: { uses: ["spring"], usedIn: [] },
	useTouchScreen: { uses: [], usedIn: [] },
	MultiselectInput: {
		uses: [
			"ChoiceField",
			"ChoiceIndicatorMulti",
			"ChoiceIndicatorRadio",
			"ChoiceIndicatorToggle",
			"Field",
		],
		usedIn: [],
	},
	ButtonMultiSelectInput: {
		uses: ["Button", "ChoiceIndicatorMulti", "Field"],
		usedIn: [],
	},
	ToggleInput: {
		uses: [
			"ChoiceField",
			"ChoiceIndicatorMulti",
			"ChoiceIndicatorRadio",
			"ChoiceIndicatorToggle",
			"Field",
		],
		usedIn: [],
	},
	NumberInput: { uses: ["Field", "InputFrame"], usedIn: ["UnitNumberInput"] },
	SliderInput: { uses: ["Field", "InputFrame"], usedIn: [] },
	UnitNumberInput: { uses: ["NumberInput"], usedIn: [] },
	PasswordInput: {
		uses: ["Button", "Field", "Icon", "IconSwap", "InputFrame"],
		usedIn: [],
	},
	ComboboxTextInput: {
		uses: [
			"Button",
			"Dropdown",
			"Field",
			"InputFrame",
			"Listbox",
			"Text",
			"dropdownStyles",
		],
		usedIn: [],
	},
	TextAreaInput: { uses: ["Field", "InputFrame"], usedIn: [] },
	TextInput: { uses: ["Field", "InputFrame"], usedIn: [] },
	EditableTextField: {
		uses: ["Button", "Field", "InputFrame", "Text"],
		usedIn: [],
	},
	EmailInput: { uses: ["Field", "InputFrame"], usedIn: [] },
	RadioInput: {
		uses: [
			"ChoiceField",
			"ChoiceIndicatorMulti",
			"ChoiceIndicatorRadio",
			"ChoiceIndicatorToggle",
			"Field",
		],
		usedIn: [],
	},
	DateRangeInput: {
		uses: [
			"Button",
			"CalendarPopover",
			"Dropdown.Panel",
			"Field",
			"InputFrame",
		],
		usedIn: [],
	},
	DateInput: {
		uses: ["CalendarPopover", "Dropdown.Panel", "Field", "InputFrame"],
		usedIn: [],
	},
	SignatureInput: {
		uses: ["Button", "Field", "InputFrame"],
		usedIn: [],
	},
	PhoneInput: {
		uses: [
			"Button",
			"Dropdown",
			"Field",
			"Icon",
			"IconSwap",
			"InputFrame",
			"Listbox",
			"Text",
			"dropdownStyles",
		],
		usedIn: [],
	},
	ProfilePictureInput: {
		uses: ["Button", "Field", "Icon", "ProfilePicture"],
		usedIn: [],
	},
	SelectInput: {
		uses: [
			"Button",
			"Dropdown",
			"Field",
			"Icon",
			"InputFrame",
			"Listbox",
			"Text",
			"dropdownStyles",
		],
		usedIn: [],
	},
	ComboboxMultiSelectInput: {
		uses: [
			"Button",
			"ChoiceIndicatorMulti",
			"ChoiceIndicatorRadio",
			"ChoiceIndicatorToggle",
			"Dropdown",
			"Field",
			"Icon",
			"InputFrame",
			"Listbox",
			"Text",
			"dropdownStyles",
		],
		usedIn: [],
	},
	ChoiceIndicatorRadio: {
		uses: ["Icon", "focus"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"MultiselectInput",
			"RadioInput",
			"ToggleInput",
		],
	},
	ChoiceIndicatorMulti: {
		uses: ["Icon", "focus"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"MultiselectInput",
			"RadioInput",
			"ToggleInput",
		],
	},
	ChoiceIndicatorToggle: {
		uses: ["Icon", "focus"],
		usedIn: [
			"ComboboxMultiSelectInput",
			"MultiselectInput",
			"RadioInput",
			"ToggleInput",
		],
	},
	ChoiceField: {
		uses: ["Text"],
		usedIn: ["MultiselectInput", "RadioInput", "ToggleInput"],
	},
	FileInput: {
		uses: ["Button", "Field", "FilePreview", "IdleState"],
		usedIn: [],
	},
	Skeleton: { uses: [], usedIn: ["Button", "ProfilePicture", "Text"] },
	SegmentedControl: {
		uses: ["Button", "Icon", "Text", "spring"],
		usedIn: [],
	},
	SocialLinks: {
		uses: ["Button", "Icon", "iconRegistry"],
		usedIn: ["Footer"],
	},
	CopyStatusIcon: {
		uses: ["Icon", "IconSwap"],
		usedIn: [
			"CopyField",
			"EmailInput",
			"PasswordInput",
			"TextInput",
			"useCopyAction",
		],
	},
	useCopyAction: {
		uses: ["CopyStatusIcon", "showToast"],
		usedIn: ["CopyField", "EmailInput", "PasswordInput", "TextInput"],
	},
	CopyField: {
		uses: ["Button", "CopyStatusIcon", "Text", "useCopyAction"],
		usedIn: [],
	},
	IdleState: { uses: ["StateIndicator"], usedIn: [] },
	StateIndicator: {
		uses: ["Button", "Icon", "Text"],
		usedIn: ["ErrorState", "IdleState"],
	},
	ErrorState: {
		uses: ["Icon", "StateIndicator"],
		usedIn: ["SuspenseBoundary"],
	},
	Accordion: {
		uses: ["Button", "Card", "Icon", "Text", "spring"],
		usedIn: [],
	},
	SuspenseBoundary: {
		uses: ["ErrorState", "Loader", "motionTiming"],
		usedIn: [],
	},
	ImageSwitcher: {
		uses: ["Image", "PaginationControls", "motionTiming"],
		usedIn: [],
	},
	PaginationControls: {
		uses: ["Button", "Icon", "Text"],
		usedIn: ["ImageSwitcher"],
	},
	ScrollBorders: {
		uses: ["Button", "focus", "motionTiming"],
		usedIn: [],
	},
	Tooltip: {
		uses: ["Dropdown", "Text"],
		usedIn: [],
	},
	Loader: {
		uses: ["Icon"],
		usedIn: [
			"Button",
			"HealthCheckIndicator",
			"ImageInspectModal",
			"SuspenseBoundary",
		],
	},
	HealthCheckIndicator: {
		uses: ["Button", "Chip", "Loader", "Text"],
		usedIn: [],
	},
	ProfilePicture: {
		uses: ["Chip", "Skeleton", "Text"],
		usedIn: ["ProfilePictureInput"],
	},
	FilePreview: {
		uses: [
			"Button",
			"FileInspectModal",
			"InspectableImage",
			"Chip",
			"Text",
			"useConfirmationModal",
			"useModal",
		],
		usedIn: ["FileInput"],
	},
	FileInspectModal: {
		uses: ["Button", "Text"],
		usedIn: ["FilePreview"],
	},
	InspectableImage: {
		uses: ["Button", "useImageInspectModal"],
		usedIn: ["FilePreview"],
	},
	Portal: { uses: [], usedIn: ["Dropdown", "ModalShell", "ToastHost"] },
	ConfirmationModal: {
		uses: ["Button", "Text"],
		usedIn: ["useConfirmationModal"],
	},
	useConfirmationModal: {
		uses: ["ConfirmationModal", "useModal"],
		usedIn: ["FilePreview"],
	},
	ModalShell: {
		uses: ["Portal"],
		usedIn: ["ModalHost"],
	},
	ModalCard: {
		uses: ["Card"],
		usedIn: ["ModalHost", "DashboardCommandProvider"],
	},
	useImageInspectModal: {
		uses: ["ImageInspectModal", "useModal"],
		usedIn: ["InspectableImage"],
	},
	ModalHost: {
		uses: ["ModalCard", "ModalShell"],
		usedIn: ["ModalClientMount"],
	},
	useModal: {
		uses: [],
		usedIn: ["useConfirmationModal", "useImageInspectModal"],
	},
	ImageInspectModal: {
		uses: ["Button", "Loader", "Reveal.Image"],
		usedIn: ["useImageInspectModal"],
	},
	ToastHost: {
		uses: ["Button", "Icon", "IconSwap", "Card", "Portal", "Text", "spring"],
		usedIn: ["ToastClientMount"],
	},
	showToast: {
		uses: [],
		usedIn: ["CopyField", "ImageInspectModal", "ToastHost"],
	},
};
