export const applicationSurfaces = {
	dashboardReferenceEntities: {
		ownedPaths: [
			"docs/frontend-entity-policy.md",
			"scripts/verify/verify-reference-entities.ts",
			"scripts/verify/verify-entity-deletion.ts",
			"scripts/verify/verify-mutation-policy.ts",
			"scripts/verify/verify-entity-skeletons.ts",
			"scripts/verify/verify-frontend-entity-policy.ts",
			"src/app/(site)/dashboard/records",
			"src/app/(site)/dashboard/organization/members/[memberId]",
			"src/app/(site)/dashboard/reference",
			"src/app/(site)/dashboard/_components/commands/DashboardEntityCommands.tsx",
			"src/app/(site)/dashboard/_components/entities/EntityDeletion.tsx",
			"src/app/(site)/dashboard/_components/entities/record",
			"src/app/(site)/dashboard/_lib/entities/record",
			"src/app/(site)/dashboard/_lib/entity-lifecycle.ts",
			"src/app/(site)/dashboard/_lib/fixtures",
		],
		packageScripts: [
			"verify:reference-entities",
			"verify:entity-deletion",
			"verify:mutation-policy",
			"verify:entity-skeletons",
			"verify:frontend-entity-policy",
			"verify:frontend-entities",
		],
	},
	dashboard: {
		ownedPaths: [
			"docs/auth-organization-adapters.md",
			"docs/dashboard-page-policy.md",
			"scripts/verify/verify-auth-organization.ts",
			"scripts/verify/verify-dashboard-page-policy.ts",
			"scripts/verify/verify-dashboard-surfaces.ts",
			"scripts/verify/verify-platform-operations.ts",
			"src/app/(site)/_components/organization",
			"src/app/(site)/dashboard",
			"src/app/(site)/(auth)",
			"src/app/api/auth",
			"src/app/api/debug",
			"src/app/api/feedback",
			"src/app/api/platform",
			"src/app/api/support",
			"src/lib/api/auth.ts",
			"src/lib/auth",
			"src/lib/template-intelligence/dashboard-domain.tsx",
		],
		packageScripts: [
			"verify:auth",
			"verify:dashboard-pages",
			"verify:dashboard",
			"verify:platform",
		],
	},
};
