export const applicationSurfaces = {
	assistant: {
		ownedPaths: [
			"src/app/(site)/dashboard/_components/entities/record/RecordToolCall.catalog.tsx",
			"src/app/(site)/dashboard/_components/entities/record/RecordToolCall.stories.tsx",
			"src/app/(site)/dashboard/_components/entities/record/RecordToolCall.tsx",
			"src/app/(site)/dashboard/assistant",
			"src/app/api/assistant",
			"src/components/domain/assistant",
			"src/lib/assistant/access.server.ts",
			"src/lib/assistant/approval.server.ts",
			"src/lib/assistant/codex-harness.server.ts",
			"src/lib/assistant/fixture.ts",
			"src/lib/assistant/records.server.ts",
			"src/lib/assistant/runs.server.ts",
			"src/lib/assistant/runtime.server.ts",
			"src/lib/assistant/server.ts",
			"src/lib/assistant/tool-input-stream.server.ts",
			"scripts/verify/verify-assistant.ts",
		],
		packageDependencies: ["@ai-sdk/openai", "@ai-sdk/react", "ai"],
		packageScripts: ["verify:assistant"],
	},
	dashboard: {
		ownedPaths: [
			"src/config/surfaces/auth.ts",
			"src/config/surfaces/dashboard.ts",
			"docs/guides/auth-organization-adapters.md",
			"scripts/verify/verify-auth-organization.ts",
			"scripts/verify/verify-dashboard-page-policy.ts",
			"scripts/verify/verify-dashboard-surfaces.ts",
			"scripts/verify/verify-reference-entities.ts",
			"scripts/verify/verify-entity-deletion.ts",
			"scripts/verify/verify-mutation-policy.ts",
			"scripts/verify/verify-entity-skeletons.ts",
			"scripts/verify/verify-frontend-entity-policy.ts",
			"scripts/verify/verify-platform-operations.ts",
			"src/app/(site)/_components/organization",
			"src/app/(site)/dashboard",
			"src/app/(site)/(auth)",
			"src/app/api/auth",
			"src/app/api/debug",
			"src/app/api/feedback",
			"src/app/api/platform",
			"src/app/api/support",
			"src/lib/api/auth.ts",
			"src/lib/auth",
			"src/lib/template-intelligence/dashboard-domain.tsx",
		],
		packageScripts: [
			"verify:auth",
			"verify:dashboard-pages",
			"verify:dashboard",
			"verify:reference-entities",
			"verify:entity-deletion",
			"verify:mutation-policy",
			"verify:entity-skeletons",
			"verify:frontend-entity-policy",
			"verify:frontend-entities",
			"verify:platform",
		],
	},
};
