export const devToolSurfaces = {
	demo: {
		ownedPaths: ["src/app/(site)/(dev)/internal/demo"],
	},
	intelligence: {
		ownedPaths: [
			".codex/hooks.json",
			"src/app/(site)/dashboard/_components/intelligence",
			"src/app/(site)/(dev)/internal/intelligence",
			"src/lib/template-intelligence",
			"scripts/generate-template-intelligence.mjs",
			"scripts/lib/codex-turn-recording.mjs",
			"scripts/lib/template-intelligence-benchmark.mjs",
			"scripts/record-codex-turn-event.mjs",
			"scripts/record-template-intelligence-benchmark.mjs",
			"scripts/clear-template-intelligence-benchmark.mjs",
			"scripts/run-template-intelligence-benchmark.mjs",
			"scripts/run-template-intelligence-hybrid.mjs",
			"scripts/setup-template-intelligence-serena.mjs",
			"scripts/template-intelligence-serena-service.mjs",
			"scripts/verify/verify-template-intelligence-benchmark.mjs",
			"scripts/verify/verify-codex-turn-recording.ts",
			"docs/template-intelligence.md",
			"docs/worklogs/template-intelligence-ledger.md",
			"docs/worklogs/template-intelligence-handoff.md",
			"docs/worklogs/template-intelligence-review-handoff.md",
			"docs/worklogs/template-intelligence-benchmark.md",
			"docs/worklogs/template-intelligence-benchmark-runs.jsonl",
			"docs/worklogs/template-intelligence-benchmark-runs.example.jsonl",
		],
		packageScripts: [
			"intelligence:generate",
			"intelligence:ensure",
			"intelligence:query",
			"intelligence:benchmark",
			"intelligence:record",
			"intelligence:record:clear",
			"intelligence:hybrid",
			"intelligence:serena:debug",
			"intelligence:serena:ensure",
			"intelligence:serena:setup",
			"intelligence:serena:start",
			"intelligence:serena:status",
			"intelligence:serena:stop",
			"verify:intelligence-benchmark",
			"verify:intelligence-recording",
			"predev",
			"predev:user",
			"predev:agent",
			"prebuild",
		],
	},
	scrollPerformance: {
		ownedPaths: [
			"scripts/scroll-performance",
			"docs/worklogs/scroll-performance-benchmark.md",
			"docs/worklogs/scroll-performance-runs.example.jsonl",
		],
		packageScripts: [
			"measure:scroll-performance",
			"record:scroll-performance",
			"setup:scroll-performance-autoresearch",
			"score:scroll-performance",
		],
		packageDependencies: ["playwright"],
	},
	playground: {
		ownedPaths: ["src/app/(site)/(dev)/internal/playground"],
	},
	dictionary: {
		ownedPaths: ["src/app/(site)/(dev)/internal/dictionary"],
	},
	reference: {
		ownedPaths: ["src/app/(site)/(dev)/internal/reference"],
	},
};
