// components/ui/icons/phosphorRegistry.tsx
"use client";

import {
	Archive,
	ArrowClockwise,
	ArrowCounterClockwise,
	ArrowRight,
	ArrowSquareOut,
	ArrowUpIcon,
	At,
	Bell,
	Buildings,
	Calendar,
	Cards,
	CaretDown,
	CaretLeftIcon,
	CaretRightIcon,
	ChatCircleDots,
	Check,
	ClockCounterClockwise,
	Code,
	Copy,
	Database,
	DiscordLogo,
	DotsThree,
	DotsThreeVertical,
	EnvelopeSimple,
	Eye,
	EyeClosed,
	FlagIcon,
	Gear,
	GithubLogo,
	HouseIcon,
	ImageSquare,
	InstagramLogo,
	LinkedinLogo,
	LinkSimple,
	List,
	ListBullets,
	ListChecks,
	ListNumbers,
	Lock,
	MagnifyingGlass,
	MetaLogo,
	Minus,
	Paperclip,
	PaperPlaneTilt,
	PencilSimpleIcon,
	Plus,
	PushPin,
	Question,
	Quotes,
	ShieldCheck,
	SidebarSimple,
	SignOut,
	SlidersHorizontal,
	Sparkle,
	Spinner,
	Star,
	Stop,
	Table,
	TextB,
	TextH,
	TextItalic,
	TextStrikethrough,
	TextT,
	TextUnderline,
	TiktokLogo,
	Trash,
	TreeStructure,
	User,
	UsersThree,
	WarningCircle,
	X,
	XLogo,
	YoutubeLogo,
} from "@phosphor-icons/react";
import {
	createIconRegistry,
	type IconRegistry,
} from "@/components/ui/icons/iconRegistry";

const phosphorOverrides: Partial<IconRegistry> = {
	archive: Archive,
	at: At,
	bold: TextB,
	code: Code,
	"arrow-right": ArrowRight,
	"external-link": ArrowSquareOut,
	"caret-left": CaretLeftIcon,
	"caret-right": CaretRightIcon,
	bell: Bell,
	building: Buildings,
	calendar: Calendar,
	cards: Cards,
	chat: ChatCircleDots,
	chevron: CaretDown,
	"chevron-down": CaretDown,
	check: Check,
	copy: Copy,
	database: Database,
	discord: DiscordLogo,
	ellipsis: DotsThree,
	"ellipsis-vertical": DotsThreeVertical,
	mail: EnvelopeSimple,
	eye: Eye,
	"eye-closed": EyeClosed,
	github: GithubLogo,
	instagram: InstagramLogo,
	"arrow-up": ArrowUpIcon,
	"linked-in": LinkedinLogo,
	link: LinkSimple,
	lock: Lock,
	paperclip: Paperclip,
	pin: PushPin,
	send: PaperPlaneTilt,
	menu: List,
	meta: MetaLogo,
	minus: Minus,
	search: MagnifyingGlass,
	plus: Plus,
	question: Question,
	quote: Quotes,
	redo: ArrowClockwise,
	spinner: Spinner,
	sparkle: Sparkle,
	sliders: SlidersHorizontal,
	strikethrough: TextStrikethrough,
	table: Table,
	"text-format": TextT,
	tiktok: TiktokLogo,
	underline: TextUnderline,
	undo: ArrowCounterClockwise,
	close: X,
	cross: X,
	flag: FlagIcon,
	gear: Gear,
	home: HouseIcon,
	heading: TextH,
	history: ClockCounterClockwise,
	image: ImageSquare,
	italic: TextItalic,
	"list-bulleted": ListBullets,
	"list-checks": ListChecks,
	"list-numbered": ListNumbers,
	"list-structure": TreeStructure,
	"log-out": SignOut,
	shield: ShieldCheck,
	"sidebar-collapse": SidebarSimple,
	pencil: PencilSimpleIcon,
	trash: Trash,
	user: User,
	users: UsersThree,
	warning: WarningCircle,
	star: Star,
	stop: Stop,
	x: XLogo,
	youtube: YoutubeLogo,
};

export const phosphorIconRegistry = createIconRegistry(phosphorOverrides);
