export const assemblyGeneratedPaths = new Set([
	"AGENTS.md",
	"README.md",
	"next.config.ts",
	"package-lock.json",
	"package.json",
	"src/config/surfaces.ts",
	"src/lib/api/index.ts",
	"src/lib/marketing-content/source.ts",
	"tsconfig.json",
]);

export const assemblyTemplateOnlyPaths = new Set([
	"docs/guides/186-backport-ledger.md",
	"docs/guides/components/design-system-agent-benchmark.md",
	"docs/guides/components/fixtures/design-system-agent-benchmark-runs.jsonl",
	"docs/guides/components/fixtures/design-system-agent-benchmark-runs.md",
	"scripts/create-template-profile.mjs",
	"scripts/dev-thin.mjs",
	"scripts/generate-commit-line-delta.mjs",
	"scripts/generate-template-assembly-inventory.mjs",
	"scripts/install-orchestration.mjs",
	"scripts/measure-storybook-performance.mjs",
	"scripts/review-thin-start-api.mjs",
	"scripts/verify/verify-design-system-agent-benchmark.mjs",
	"scripts/verify/verify-template-profiles.mjs",
	".github/workflows/update-commit-line-delta.yml",
	"docs/assets/commit-line-delta.svg",
]);

export const assemblyTemplateOnlyRoots = [
	".agents",
	"plugins",
	"template-assembly",
	"template-profiles",
	"template-surfaces",
];

export const assemblyCoreRoots = [
	".env.example",
	".gitignore",
	".storybook",
	".vercelignore",
	".vscode",
	"biome.json",
	"docs",
	"next-sitemap.config.js",
	"postcss.config.mjs",
	"public",
	"scripts",
	"src",
	"vitest.config.mts",
	"vitest.shims.d.ts",
];

export const assemblyTemplateOnlyScripts = new Set([
	"create:project",
	"orchestration:init",
	"dev:thin",
	"chart:commit-line-delta",
	"review:thin-start-api",
	"measure:storybook-performance",
	"generate:design-system-agent-benchmark-report",
	"verify:design-system-agent-benchmark",
	"verify:storybook-backport",
	"verify:profiles",
]);

export const assemblyTemplateOnlyDevDependencies = new Set([]);

export const assemblyCoreScripts = new Set([
	"dev",
	"dev:preview",
	"dev:local",
	"dev:inspect",
	"dev:user",
	"dev:agent",
	"predev:preview",
	"predev:local",
	"predev:inspect",
	"build-storybook",
	"build",
	"design-system:evidence",
	"start",
	"lint",
	"typecheck",
	"verify:static",
	"verify:build",
	"verify:smoke",
	"verify:modals",
	"verify:surface-contracts",
	"verify:route-surfaces",
	"verify:component-skeletons",
	"verify:route-skeletons",
	"storybook",
	"storybook:preview",
	"storybook:status",
	"storybook:stop",
	"test-storybook",
	"test-storybook:ui:light",
	"test-storybook:ui:dark",
	"test-storybook:ui",
	"verify",
	"verify:design-system-evidence",
	"verify:storybook-catalog",
	"verify:storybook-preview",
	"format",
	"postinstall",
	"postbuild",
]);

export const assemblyCoreDependencies = new Set([
	"@mdxeditor/editor",
	"@phosphor-icons/react",
	"@radix-ui/react-slot",
	"@tanstack/react-hotkeys",
	"class-variance-authority",
	"clsx",
	"libphonenumber-js",
	"micromark",
	"micromark-extension-directive",
	"micromark-extension-mdx-jsx",
	"micromark-extension-mdx-md",
	"motion",
	"next",
	"next-sitemap",
	"react",
	"react-dom",
	"react-markdown",
	"react-phone-number-input",
	"remark-gfm",
	"sonner",
	"streamdown",
]);

export const assemblyCoreDevDependencies = new Set([
	"@biomejs/biome",
	"@chromatic-com/storybook",
	"@storybook/addon-a11y",
	"@storybook/addon-docs",
	"@storybook/addon-vitest",
	"@storybook/nextjs-vite",
	"@tailwindcss/postcss",
	"@types/node",
	"@types/react",
	"@types/react-dom",
	"@vitest/browser-playwright",
	"@vitest/coverage-v8",
	"code-inspector-plugin",
	"playwright",
	"storybook",
	"tailwindcss",
	"tsx",
	"typescript",
	"vite",
	"vitest",
]);

export const assemblyProjectDocs = new Set([
	"docs/guides/auth-organization-adapters.md",
	"docs/guides/components/README.md",
	"docs/guides/components/composition-and-public-apis.md",
	"docs/guides/components/feedback-and-status.md",
	"docs/guides/components/forms-and-submission.md",
	"docs/guides/components/interaction-and-responsive-rendering.md",
	"docs/guides/components/loading-and-async-states.md",
	"docs/guides/components/overlays-and-confirmation.md",
	"docs/guides/components/surfaces-and-presentation.md",
	"docs/guides/payload-vercel-neon-blob.md",
]);

export function isWithinPath(relativePath, ownedPath) {
	return relativePath === ownedPath || relativePath.startsWith(`${ownedPath}/`);
}
